package com.example.lyubodeeva_lesson2

object DataStorage {
    fun getVacancyList(): List<VacancyBtnData> {
        return listOf(
            VacancyBtnData("Android trainee",
            "Стажировка по направлению Android",
            R.drawable.logo),
            VacancyBtnData("SRE Engineer",
                "Админиcтрирование и поддержка кластера Kubernetes",
                R.drawable.logo),
            VacancyBtnData("Analyst 1C",
                "Внедрение и поддержка крупных проектов",
                R.drawable.logo),
            VacancyBtnData("System Analyst",
                "Участие в проектах по разработке/доработке ИТ-систем",
                R.drawable.logo),
            VacancyBtnData("Вusiness analyst/System analyst",
                "Создание уникальных решений для управления инвестиционными продуктами",
                R.drawable.logo),
            VacancyBtnData("HRD/Head of recruitment",
                "Выполнение политик и процедур работы с персоналом",
                R.drawable.logo),
            VacancyBtnData("Программист 1С",
                "Разработка на платформе 1С",
                R.drawable.logo),
            VacancyBtnData("Android Developer",
                "Разработка offline-first мессенджера на Kotlin",
                R.drawable.logo),
            VacancyBtnData("Java developer",
                "Создание Fintech-решений",
                R.drawable.logo),
            VacancyBtnData("Java Developer Trainee",
                "Стажировка под руководством опытных кураторов",
                R.drawable.logo),
            VacancyBtnData("Android Developer",
                "Работа с формами страхования",
                R.drawable.logo),
            VacancyBtnData("Solution Architect",
                "Создание CRM-системы с нуля",
                R.drawable.logo),
            VacancyBtnData("Администратор баз данных",
                "Сопровождение работы СУБД, обеспечение непрерывности сервиса",
                R.drawable.logo),
            VacancyBtnData("Менеджер по продажам",
                "Активные продажи. Выполнение плана продаж. Работа с готовой клиентской базой, без поиска",
                R.drawable.logo),
            VacancyBtnData("Менеджер по продажам рекламы",
                "Активный поиск и привлечение новых клиентов на размещение рекламы в журнале",
                R.drawable.logo),
            VacancyBtnData("Staff Coordinator",
                "Контроль и планирование кадрового потока в рамках компании",
                R.drawable.logo),
            VacancyBtnData("QA Automation Python Engineer",
                "Написание автоматизированных тестов с помощью Pytest",
                R.drawable.logo),
            VacancyBtnData("UNIX developer",
                "Разработка драйверов устройств FreeBSD",
                R.drawable.logo),
            VacancyBtnData("React Developer (Full-Stack Developer)",
                "Разработка программного обеспечения",
                R.drawable.logo),
            VacancyBtnData("IT-Recruiter",
                "Работа с актуальными вакансиями, поиск и подбор персонала",
                R.drawable.logo)
        )
    }
    fun getOfficeList(): List<OfficeData>{
        return listOf(
            OfficeData("Москва"),
            OfficeData("Казань"),
            OfficeData("Ростов-на Дону"),
            OfficeData("Минск"),
            OfficeData("Гомель"),
        )
    }
}
